name: Deploy Next.js to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/html/RefuerzoEscolarWeb/refuerzo-web
            sudo git pull origin main
            sudo npm install
            sudo npm run build
            pm2 restart refuerzo-web 